# Generated by Django 6.1.1 on 2026-09-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ficha',
            name='chk_fichas_nivel_digitalizacion',
        ),
        migrations.AddField(
            model_name='ficha',
            name='analisis_requisitos_json',
            field=models.JSONField(blank=True, default=list, help_text='Lista de objetos {requisito: string, observacion: string}', null=True, verbose_name='Análisis de requisitos (Clave-Valor)'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='cantidad_personas_intervienen',
            field=models.IntegerField(blank=True, help_text='Número de personas que intervienen en el proceso (>= 0)', null=True, verbose_name='Cantidad de personas que intervienen'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='conceptos_con_fundamento',
            field=models.JSONField(blank=True, default=list, help_text='Lista de conceptos fundamentados (tramite_o_servicio, requisitos, plazo_de_resolucion, vigencia)', null=True, verbose_name='Conceptos con fundamento'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='formas_de_pago',
            field=models.JSONField(blank=True, default=list, help_text='Caja propia, Bancos, Banca electrónica, Otros', null=True, verbose_name='Formas de pago'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='importe_tramite',
            field=models.CharField(blank=True, help_text='Importe expresado en string', max_length=255, null=True, verbose_name='Importe del trámite'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='numero_requisitos',
            field=models.IntegerField(blank=True, help_text='Número de requisitos que posee el trámite/servicio', null=True, verbose_name='Número de requisitos'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='regulacion_faculta_organo',
            field=models.TextField(blank=True, help_text='Nombre de la regulación que faculta al órgano administrativo', null=True, verbose_name='Regulación que faculta al órgano administrativo'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='tipo_tramite_dirigido',
            field=models.CharField(blank=True, help_text='Ciudadano, Empresarial o Ambos', max_length=100, null=True, verbose_name='Tipo de trámite o servicio'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='unidad_de_cobro',
            field=models.CharField(blank=True, help_text='UMAs, Moneda Nacional o Gratuito', max_length=100, null=True, verbose_name='Unidad de cobro'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='status',
            field=models.IntegerField(choices=[(0, 'Borrador'), (1, 'Enviada'), (2, 'Aprobada'), (3, 'Observada'), (4, 'Rechazada')], default=0, help_text='0=borrador, 1=enviada, 2=aprobada, 3=observada, 4=rechazada', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='areas_administrativas_interfieren',
            field=models.IntegerField(blank=True, help_text='Número de áreas administrativas involucradas en el proceso (>= 0)', null=True, verbose_name='Áreas administrativas que intervienen'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='cuellos_de_botella',
            field=models.TextField(blank=True, help_text='¿Dónde están los cuellos de botella generados?', null=True, verbose_name='Cuellos de botella'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='fundamento_en_ley_de_ingresos',
            field=models.TextField(blank=True, help_text='Referencia al fundamento en la Ley de Ingresos', null=True, verbose_name='Fundamento en Ley de Ingresos'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='is_dia_habil_o_inhabil',
            field=models.BooleanField(blank=True, help_text='True = días hábiles, False = días naturales/inhábiles', null=True, verbose_name='¿Días hábiles?'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='nivel_digitalizacion_actual',
            field=models.IntegerField(blank=True, choices=[(0, 'Presencial (Legacy)'), (1, 'Nivel 1: La información del trámite o servicio está publicada en medios electrónicos'), (2, 'Nivel 2: Los formatos del trámite o servicio están disponibles electrónicamente'), (3, 'Nivel 3: El usuario puede iniciar la gestión, recibir o reenviar la información del trámite'), (4, 'Nivel 4: El trámite o servicio se gestiona desde el inicio hasta el final a través de un medio electrónico')], help_text='1=Nivel 1 Informativo, 2=Nivel 2 Formatos, 3=Nivel 3 Interactivo, 4=Nivel 4 Digital End-to-End', null=True, verbose_name='Nivel de digitalización actual'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='propuestas_de_mejora',
            field=models.TextField(blank=True, help_text='¿Indique propuesta de mejora de los problemas detectados?', null=True, verbose_name='Propuestas de mejora'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='regulacion_fundamenta_existencia_tramite',
            field=models.TextField(blank=True, help_text='Nombre, artículo y fracción de la regulación en la que se fundamenta el trámite o servicio', null=True, verbose_name='Regulación que fundamenta el trámite'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='requisitos_sin_valor',
            field=models.TextField(blank=True, help_text='¿Qué requisitos no agregan valor al resolutivo del trámite?', null=True, verbose_name='Requisitos sin valor'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='resoluciones_positivas',
            field=models.IntegerField(blank=True, help_text='Número de resoluciones positivas del ejercicio anterior (>= 0)', null=True, verbose_name='Resoluciones positivas'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='solicitud_tipo',
            field=models.IntegerField(blank=True, choices=[(0, 'No tiene'), (1, 'Escrito libre'), (2, 'Formato específico'), (3, 'Formato único')], help_text='0=No tiene, 1=Escrito libre, 2=Formato específico, 3=Formato único', null=True, verbose_name='Tipo de solicitud'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='solicitudes_recibidas_semestre_anterior',
            field=models.IntegerField(blank=True, help_text='Número de solicitudes recibidas en el ejercicio inmediato anterior (>= 0)', null=True, verbose_name='Solicitudes recibidas ejercicio anterior'),
        ),
        migrations.AddConstraint(
            model_name='ficha',
            constraint=models.CheckConstraint(condition=models.Q(('nivel_digitalizacion_actual__isnull', True), models.Q(('nivel_digitalizacion_actual__gte', 0), ('nivel_digitalizacion_actual__lte', 4)), _connector='OR'), name='chk_fichas_nivel_digitalizacion'),
        ),
    ]
