# Generated by Django 6.1.1 on 2026-09-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_remove_ficha_chk_fichas_nivel_digitalizacion_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tramiteoservicio',
            name='chk_tramites_tipo',
        ),
        migrations.AlterField(
            model_name='tramiteoservicio',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(0, 'Trámite presencial'), (1, 'Trámite digital'), (2, 'Servicio presencial'), (3, 'Servicio digital'), (4, 'Mixto'), (5, 'Vía telefónica')], help_text='0=trámite presencial, 1=trámite digital, 2=servicio presencial, 3=servicio digital, 4=mixto', null=True, verbose_name='Tipo'),
        ),
        migrations.AddConstraint(
            model_name='tramiteoservicio',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__isnull', True), models.Q(('tipo__gte', 0), ('tipo__lte', 5)), _connector='OR'), name='chk_tramites_tipo'),
        ),
    ]
