# Generated by Django 5.2.17 on 2026-09-21 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_remove_tramiteoservicio_chk_tramites_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='importe_tramite',
            field=models.FloatField(blank=True, help_text='Importe numérico en Moneda Nacional o equivalente (>= 0)', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Importe del trámite'),
        ),
    ]
