# Generated by Django 5.2.17 on 2026-09-21 14:40

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_niveles(apps, schema_editor):
    Ficha = apps.get_model('src', 'Ficha')
    FichaNivelDigitalizacion = apps.get_model('src', 'FichaNivelDigitalizacion')
    for ficha in Ficha.objects.exclude(nivel_digitalizacion_actual__isnull=True):
        FichaNivelDigitalizacion.objects.get_or_create(
            id_ficha=ficha,
            nivel=ficha.nivel_digitalizacion_actual
        )


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_ficha_importe_tramite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='nivel_digitalizacion_actual',
            field=models.IntegerField(blank=True, choices=[(0, 'Presencial (Legacy)'), (1, 'Nivel 1: La información del trámite o servicio está publicada en medios electrónicos'), (2, 'Nivel 2: Los formatos del trámite o servicio están disponibles electrónicamente'), (3, 'Nivel 3: El usuario puede iniciar la gestión, recibir o reenviar la información del trámite'), (4, 'Nivel 4: El trámite o servicio se gestiona desde el inicio hasta el final a través de un medio electrónico')], help_text='DEPRECADO — Utilizar fichas_has_niveles_digitalizacion para selección múltiple', null=True, verbose_name='Nivel de digitalización actual'),
        ),
        migrations.CreateModel(
            name='FichaNivelDigitalizacion',
            fields=[
                ('id_ficha_nivel_digitalizacion', models.BigAutoField(db_column='id_ficha_nivel_digitalizacion', primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(choices=[(0, 'Nivel 0: Presencial'), (1, 'Nivel 1: Informativo'), (2, 'Nivel 2: Interactivo parcial'), (3, 'Nivel 3: Digital end-to-end'), (4, 'Nivel 4: Automatizado')], help_text='0=Presencial, 1=Informativo, 2=Interactivo parcial, 3=Digital end-to-end, 4=Automatizado', verbose_name='Nivel de madurez digital')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('id_ficha', models.ForeignKey(db_column='id_ficha', help_text='Ficha asociada (ON DELETE CASCADE)', on_delete=django.db.models.deletion.CASCADE, related_name='niveles_digitalizacion', to='src.ficha', verbose_name='Ficha')),
            ],
            options={
                'verbose_name': 'Ficha Nivel Digitalización',
                'verbose_name_plural': 'Fichas Niveles Digitalización',
                'db_table': 'fichas_has_niveles_digitalizacion',
                'ordering': ['id_ficha', 'nivel'],
                'constraints': [models.UniqueConstraint(fields=('id_ficha', 'nivel'), name='unique_ficha_nivel')],
            },
        ),
        migrations.RunPython(copy_existing_niveles, reverse_code=migrations.RunPython.noop),
    ]
