# Generated by Django 5.2.17 on 2026-09-21 15:40

import django.db.models.deletion
from django.db import migrations, models


def copy_tipos_atencion(apps, schema_editor):
    """
    Migra el campo legacy 'tipo' de TramiteOServicio a la nueva tabla pivote tramites_has_tipos.
    Mapeo:
      0 (Trámite presencial)  → 0 (Presencial)
      1 (Trámite digital)     → 2 (Vía Digital)
      2 (Servicio presencial) → 0 (Presencial)
      3 (Servicio digital)    → 2 (Vía Digital)
      4 (Mixto)               → 0 (Presencial) + 2 (Vía Digital)
      5 (Vía telefónica)      → 1 (Vía Telefónica)
    """
    TIPO_PRESENCIAL = 0
    TIPO_VIA_TELEFONICA = 1
    TIPO_VIA_DIGITAL = 2

    legacy_map = {
        0: [TIPO_PRESENCIAL],
        1: [TIPO_VIA_DIGITAL],
        2: [TIPO_PRESENCIAL],
        3: [TIPO_VIA_DIGITAL],
        4: [TIPO_PRESENCIAL, TIPO_VIA_DIGITAL],
        5: [TIPO_VIA_TELEFONICA],
    }

    TramiteOServicio = apps.get_model('src', 'TramiteOServicio')
    TramiteTipoAtencion = apps.get_model('src', 'TramiteTipoAtencion')

    for tramite in TramiteOServicio.objects.exclude(tipo__isnull=True):
        nuevos_tipos = legacy_map.get(tramite.tipo, [])
        for t in nuevos_tipos:
            TramiteTipoAtencion.objects.get_or_create(
                id_tramite_servicio=tramite,
                tipo=t
            )


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_fichaniveldigitalizacion_create_and_migrate_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramiteoservicio',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(0, 'Trámite presencial'), (1, 'Trámite digital'), (2, 'Servicio presencial'), (3, 'Servicio digital'), (4, 'Mixto'), (5, 'Vía telefónica')], help_text='DEPRECADO — Utilizar tramites_has_tipos para selección múltiple de modalidades de atención', null=True, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='TramiteTipoAtencion',
            fields=[
                ('id_tramite_tipo_atencion', models.BigAutoField(db_column='id_tramite_tipo_atencion', primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(0, 'Presencial'), (1, 'Vía Telefónica'), (2, 'Vía Digital')], help_text='0=Presencial, 1=Vía Telefónica, 2=Vía Digital', verbose_name='Tipo de atención')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('id_tramite_servicio', models.ForeignKey(db_column='id_tramite_servicio', help_text='Trámite o Servicio asociado (ON DELETE CASCADE)', on_delete=django.db.models.deletion.CASCADE, related_name='tipos_atencion', to='src.tramiteoservicio', verbose_name='Trámite o Servicio')),
            ],
            options={
                'verbose_name': 'Trámite Tipo Atención',
                'verbose_name_plural': 'Trámites Tipos Atención',
                'db_table': 'tramites_has_tipos',
                'ordering': ['id_tramite_servicio', 'tipo'],
                'constraints': [models.UniqueConstraint(fields=('id_tramite_servicio', 'tipo'), name='unique_tramite_tipo_atencion')],
            },
        ),
        migrations.RunPython(copy_tipos_atencion, reverse_code=migrations.RunPython.noop),
    ]

