# Generated by Django 6.1.1 on 2026-09-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_tramitetipoatencion_create_and_migrate_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='autorizo_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de quien autorizó'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='autorizo_puesto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Puesto de quien autorizó'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='elaboro_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de quien elaboró'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='elaboro_puesto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Puesto de quien elaboró'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='reviso1_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de quien revisó (1)'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='reviso1_puesto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Puesto de quien revisó (1)'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='reviso2_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de quien revisó (2)'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='reviso2_puesto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Puesto de quien revisó (2)'),
        ),
    ]
